submit exercise test="":
  #!/usr/bin/env bash
  set -euxo pipefail
  cd {{exercise}}
  if [ ! {{test}} ]; then
    ruby -I .. -r disable_skip -r minitest/pride {{replace(exercise, '-', '_')}}_test.rb
  else
    ruby -I .. -r disable_skip -r minitest/pride {{test}}_test.rb
  fi
  exercism submit
