submit exercise:
  #!/usr/bin/env bash
  set -euxo pipefail
  cd {{exercise}}
  if [ ! -d ./build ]; then
    mkdir build
    cd build
    cmake -G 'Unix Makefiles' ..
  else
    cd build
  fi
  make
  cd .. && exercism submit
